spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED}
  datasource:
    host: ${SPRING_DATASOURCE_HOST}
    port: ${SPRING_DATASOURCE_PORT}
    name: ${SPRING_DATASOURCE_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jackson:
    deserialization:
      fail-on-null-for-primitives: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
    clean-disabled: ${SPRING_FLYWAY_CLEAN_DISABLED}
    out-of-order: ${SPRING_FLYWAY_OUT_OF_ORDER}

jwt:
  secret: ${SPRING_JWT_SECRET}
  access-expiration: ${SPRING_JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${SPRING_JWT_REFRESH_EXPIRATION}

server:
  port: ${SERVER_PORT}

upload-path: ${UPLOAD_PATH}
process-api-url: ${PROCESS_API_URL}
no_of_threads: ${NO_OF_THREADS}

allowed-origin: "http://localhost:3000"

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
